### ISSUE TITLE
文字列のエスケープ処理

### ISSUE THREAD

**Issue by syohex** [aharisu/vim-gdev#1]
gosh_complete.scmの結果に出てくる文字列がエスケープ処理されて
いないので、その結果を処理するときに問題が生じることがあります。
現状の出力を JSONとして解釈できないのはこのためです。

```
% echo "#load-file doc/gauche.sequence" | gosh -I. gosh_complete.scm | python -mjson.tool  
Invalid \escape: line 1 column 1047 (char 1047)
```

これは JSONパーサが 'gauche.sequence'にある '\C'という文字列を,  エスケープ
された 'C'と解釈してしまい、JSONの規約に違反するためです。
(JSONで許可されるエスケープシーケンスは[こちら](http://www.json.org/)を参照してください)
以下のようにエスケープ処理を施してやると JSONとして解釈できます。

```
% echo "#load-file doc/gauche.sequence" | gosh -I. gosh_complete.scm | sed -e 's/\\C/\\\\C/g' | python -mjson.tool
{
    "docs": [
        {
...
    ], 
    "order": [
        "doc/gauche.sequence"
    ]
}
```

元の文字列に含まれる '\'という文字をすべて '\\'に置き換えるような
処理を加えることで対応ができるのではないかと思います。

よろしくお願いします。

**Comment by aharisu** [comment]
調べていただいてありがとうございます。
遅くなりましたが修正して、JSONとしても読めるようになりました。
